### PR TITLE
[WIP] Port Lift to SpongeAPI 4.x

### PR DESCRIPTION
**Pull request by gabizou**
This ports Lift as a SpongeAPI plugin with the latest API revision, I'll try to continue to get this to work exactly the way it should be working.

About the removed Spigot compatibility layer, I'm hoping to re-introduce it at some point, but if anything, it was simply causing issues with testing.

### CODE REVIEW

**Comment by croxis** [comment]
I haven't touched minecraft, and my job (teaching) consumes most of my mental energy so I have little oomph left to code. Are you interested in maintaining the sponge fork?

**Comment by gabizou** [comment]
@croxis I could very well do so :)

**Comment by croxis** [comment]
Let it be so! Let me Know what repo or page you would like me to point the readme to

**Comment by gabizou** [comment]
@croxis sorry for not getting back to you sooner.

My repo should be sufficient for now: https://github.com/gabizou/Lift
I'll be maintaining it for each API version release in the foreseeable future.
Would there be any suggestions as to the config version I should consider to use instead of the current `53` version?

**Comment by croxis** [comment]
Sorry about my delay. I'll leave it your hands how you want to handle versioning. I was playing on the chrome/firefox insane version numbering by bumping the version number by 1 for each release :)

**Comment by gabizou** [comment]
@croxis I figured though since I'm essentially rewriting almost the entire sponge part of the plugin, I'm moving the config over to being generated with Configurate. The temporary iteration that I've been fiddling with looks like [this](https://gist.github.com/gabizou/873d87a57dd98fbf6c9cda8ebb2bbb4d#file-liftconfig-java-L76)

**Comment by croxis** [comment]
Oh thats fine! I was fiddling with the sponge part while sponge was still
very early in development so I'm sure "best practices" has changed alot in
that time. Feel free to do whatever you want/add features/remove
features/rewrite my ugly code/etc.

On Thu, Apr 21, 2016 at 5:41 PM, Gabriel Harris-Rouquette <
notifications@github.com> wrote:

> @croxis <https://github.com/croxis> I figured though since I'm
> essentially rewriting almost the entire sponge part of the plugin, I'm
> moving the config over to being generated with Configurate. The temporary
> iteration that I've been fiddling with looks like this
> <https://gist.github.com/gabizou/873d87a57dd98fbf6c9cda8ebb2bbb4d#file-liftconfig-java-L76>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/croxis/Lift/pull/137#issuecomment-213182627>
>



-- 
- David - Proud to be saving the world since 1984

**Comment by gabizou** [comment]
@croxis so I'm assuming this PR is to be closed and/or rewritten to just mention the Sponge fork? I could write some porting of the old config if some users decided to import the old config for any reason (not sure whether they would want to, but still).

**Pull request closed without merging**
