### PR TITLE
Sign additions/fixes

### PR DESCRIPTION
**Pull request by RazihelYT**
Changed Material.WALL_SIGN to Material.LEGACY_WALL_SIGN and added sign variants.

### CODE REVIEW

**Comment by min20120907** [comment]
thx alot, it helps alot on the 1.14 versions

**Comment by min20120907** [comment]
I fixed only on oak, lol

**Comment by min20120907** [comment]
but too much mistakes bro, you didn't even change your build.gradle, and it is LEGACY not LECAGY

**Comment by RazihelYT** [comment]
> but too much mistakes bro, you didn't even change your build.gradle, and it is LEGACY not LECAGY

Sorry about that, dyslexia gets the worst of me sometimes

**Comment by croxis** [comment]
I fixed this (I think) using an alternative method. Thank you for trying though. I would of merged it back in may but I was in the middle of getting horse support in.

**Pull request closed without merging**
