### PR TITLE
Bugfixes for scrollable floor selection

### PR DESCRIPTION
**Pull request by kikelkik**
We found some bugs that I fixed:

- Something (don't know) was wrong with the equals method causing BukkitElevatorManager#run not being able to correctly remove an ended Lift. (So now just the floor blocks of an elevator are the criteria when finding an elevator from playerCache. Unfortunately, an Elevator has no field to determine equivalence. Location of the bottom floor (iron block) might have been nice.)

- When scrolling fast through floors, sometimes the currentFloor cannot be determined resulting in spamming that error message to a player. I introduced a currentFloorCache to fix this.

### CODE REVIEW

**Comment by CloudeLecaw** [comment]
https://youtu.be/1x0zAu8EK14?t=404

and why this effects your zomies now? ;)
And next one .... why it killed 100 squids? this would mean for your server the squidds still  exists...

whats going on with this autocleaner that is spamming you all time in chat? have your tired this without too?

When the screen turned black your you changed to with mfm right?..but why your mbies where effectedin secound try too?

**Comment by kikelkik** [comment]
@CloudeLecaw I think your're wrong here :D

**Comment by CloudeLecaw** [comment]
ohhhh pardon D: This comes out when you try to post from your mobilphone xD

**Comment by kikelkik** [comment]
Hey, do you have some time to review this PR? :)

**Pull request merged**
